### ISSUE TITLE
Weird Alignment of cards on index page

### ISSUE THREAD

**Issue by snitin315** [Bhaikko/mait-project#1]
The Image cards on the index page have weird alignment.
![Screenshot from 2019-11-15 17-10-26](https://user-images.githubusercontent.com/46647141/68941139-01e8a200-07cb-11ea-9363-aaa6cf94d65c.png)

![Screenshot from 2019-11-15 17-10-18](https://user-images.githubusercontent.com/46647141/68941137-001ede80-07cb-11ea-9a90-16c644b6b366.png)

**Comment by sam-mittal** [comment]
@snitin315  pls elaborate how the behavior is triggered.

**Comment by snitin315** [comment]
@sam-mittal , I will resolve the issue and make a PR as soon as possible.
